jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - task: build
    file: code/concourse/build.yml
  - put: frontbucket
resource-type:
  - name: statics3
    type: docker-image
    soruce:
      repository: thull/statucs3
resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/front.git
    branch: concourse-ci
- name: frontbucket
  type: statics3
  source:
    bucket: speakers.bris.tech
    accessKeyId: {{awsAccessKeyId}}
    secretAccessKey: {{awsSecretAccessKey}}
