resource_types:
  - name: statics3
    type: docker-image
    source:
      repository: bristechsrm/push_s3 
jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - task: build
    file: code/concourse/build.yml
  - put: frontbucket
    params: {build: gulped}
resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/front.git
    branch: master
- name: frontbucket
  type: statics3
  source:
    bucket: speakers.bris.tech
    accessKeyId: {{awsAccessKeyId}}
    secretAccessKey: {{awsSecretAccessKey}}
